config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'about', to: 'pages#about'
  get 'courses/new', to: 'courses#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

    def index

    end

    def new

    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<h1>Course Listing</h1>

<ul>
    <li>Code: CS111</li>
    <li>Name: Intro to Computer Science</li>
    <li>Description: A thorough intro to Computer Science</li>
</ul>

<ul>
    <li>Code: CS112</li>
    <li>Name: Intro to Computer Science</li>
    <li>Description: A thorough intro to Computer Science</li>
</ul> 

app/views/courses/new.html.erb
<h1>This is the new course page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnivApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'home', root_path %>
    <%= link_to 'about', about_path %>
    <%= link_to 'new course', courses_new_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>this is the about page</h1>